env:
  BUILDKITE_DOCKER_COMPOSE_CONTAINER: app

steps:
  - label: ':hotsprings: compile jar'
    command: ./mvnw package
    artifact_paths: target/*.jar
    agents:
      queue: internal
    env:
      BUILDKITE_CLEAN_CHECKOUT: true
